### ISSUE TITLE
After upgrade to pandas 1.0.0, DataFrame.ix is removed

### ISSUE THREAD

**Issue by yulijia** [asntech/intervene#37]
Hi, 

I installed the `intervene` package with `pip` command, this is a real nice and useful tool.

However, I find that if the users try to generate a pairwise plot with pandas version 1.0.0, the software will throw an error message **AttributeError: 'DataFrame' object has no attribute 'ix'**.

`.ix` is deprecated in the newest pandas package.

Could you mind updating the intervene package with the new attribute:
use `.iloc` or `.loc` instead of `.ix` at https://github.com/asntech/intervene/blob/master/intervene/modules/pairwise/pairwise.py#L150 and
https://github.com/asntech/intervene/blob/master/intervene/modules/pairwise/pairwise.py#L214

`D = D.iloc[cluster_order, cluster_order]` is for number indexing
`series = series.loc[order]` is for `str` indexing

Thanks,
Lijia

**Comment by bioinfouser** [comment]
Hi Lijia,
I am not the owner of intervene, but it works with python 2.7. Just make a new conda environment and reinstall. It should run.
Best,

**Comment by yulijia** [comment]
The same issue posted at #40

**Comment by asntech** [comment]
Hi @yulijia, Please check it now and try to install it from the source. I will make available an updated version through bioconda and pip soon.

**Comment by yulijia** [comment]
Thank you, it works now.
